# docker-compose.yml
version: "3"
services:
  database:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kevin852
      - POSTGRES_DB=udacityDB
    ports:
      - "5432"
